ARG VERSION=dev

FROM jumpserver/koko:${VERSION}-ce
ARG TARGETARCH

ARG DEPENDENCIES="                    \
        curl                          \
        git                           \
        git-lfs                       \
        iputils-ping                  \
        openssh-client                \
        telnet                        \
        unzip                         \
        vim                           \
        wget                          \
        xz-utils"

ARG APT_MIRROR=https://mirrors.ustc.edu.cn

RUN set -ex \
    && if [ -f /etc/apt/sources.list ]; then \
         sed -i "s@http://deb.debian.org@https://mirrors.ustc.edu.cn@g" /etc/apt/sources.list; \
       fi \
    && if [ -f /etc/apt/sources.list.d/debian.sources ]; then \
         sed -i "s@http://.*.debian.org@https://mirrors.ustc.edu.cn@g" /etc/apt/sources.list.d/debian.sources; \
       fi \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${DEPENDENCIES} \
    && apt-get clean
